### PR TITLE
feat: generate visitor with cmake

### PR DESCRIPTION
**Pull request by 4silvertooth**
Eliminate the manual command 
```cmake
# generate the ANTLR components (you have to setup ANTLR, before doing this step)
antlr4 -Dlanguage=Cpp -no-listener -visitor -o libs Scene.g4
```
to generate antlr components (lexer,parser,visitor) into the libs folder.

### CODE REVIEW

**Comment by gabriele-tomassetti** [comment]
Thanks for your pull request! You are right, since we now use the official build script, it makes sense to use all of its features.

**Comment by Daniel-Xu** [comment]
@4silvertooth @gabriele-tomassetti  hi folks, I'm using the simliar approach to build the demo from `runtime/Cpp`, but it keeps complaining that references are undefined.
Any ideas of how this happended?
image


Here is my cmake file:

```

# minimum required CMAKE version
CMAKE_MINIMUM_REQUIRED(VERSION 3.7 FATAL_ERROR)

list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/cmake)

# compiler must be 11 or 14
set(CMAKE_CXX_STANDARD 14)

# required if linking to static library
add_definitions(-DANTLR4CPP_STATIC)
set(ANTLR4_WITH_STATIC_CRT OFF)
# set variable pointing to the antlr tool that supports C++
# this is not required if the jar file can be found under PATH environment
set(ANTLR_EXECUTABLE ${PROJECT_SOURCE_DIR}/thirdparty/antlr-4.9.1-complete.jar)
#set(ANTLR4_ZIP_REPOSITORY ${PROJECT_SOURCE_DIR}/thirdparty/antlr4-4.9.2.zip)
set(ANTLR4_TAG 4.9.1)


# add external build for antlrcpp
include(ExternalAntlr4Cpp)
# add antrl4cpp artifacts to project environment
include_directories(${ANTLR4_INCLUDE_DIRS})

# add macros to generate ANTLR Cpp code from grammar
find_package(ANTLR REQUIRED)

# Call macro to add lexer and grammar to your build dependencies.
antlr_target(TLexer ${CMAKE_CURRENT_SOURCE_DIR}/TLexer.g4 LEXER
        PACKAGE antlrcpptest)

antlr_target(TParser ${CMAKE_CURRENT_SOURCE_DIR}/TParser.g4 PARSER
        PACKAGE antlrcpptest
        DEPENDS_ANTLR TLexer
        COMPILE_FLAGS -lib ${ANTLR_TLexer_OUTPUT_DIR})

message("----------> ${ANTLR_TLexer_OUTPUT_DIR}")
# include generated files in project environment
include_directories(${ANTLR_TLexer_OUTPUT_DIR})
include_directories(${ANTLR_TParser_OUTPUT_DIR})

add_executable(demo main.cpp
        ${ANTLR_TLexer_CXX_OUTPUTS}
        ${ANTLR_TParser_CXX_OUTPUTS})

target_link_libraries(demo antlr4_static)
```

**Comment by 4silvertooth** [comment]
Can you try `set(CMAKE_CXX_STANDARD 11)` and check if it gives errors?

**Comment by Daniel-Xu** [comment]
> Can you try `set(CMAKE_CXX_STANDARD 11)` and check if it gives errors?

Seems not, I finally figured that out: I have different version of `g++` installed on my machine and antlr is compiled with a different version.

**Pull request merged**
